import { Globe, AlertTriangle } from "lucide-react";
import { Link } from "wouter";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border/50 bg-background/80 backdrop-blur-md sticky top-0 z-50">
        <div className="container flex h-16 items-center justify-between">
          <Link href="/" className="flex items-center gap-2 cursor-pointer">
            <div className="w-8 h-8 rounded-full overflow-hidden border border-primary/20">
              <img src="/mars-ultra.png" alt="Mars" className="w-full h-full object-cover" />
            </div>
            <span className="text-xl font-bold tracking-tight">OpenMars</span>
          </Link>
        </div>
      </nav>

      <main className="container py-16 max-w-3xl">
        <div className="space-y-8">
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-yellow-500/10 border border-yellow-500/20 text-yellow-600 text-xs font-bold uppercase tracking-wider">
              <AlertTriangle className="w-3.5 h-3.5" />
              Important Notice
            </div>
            <h1 className="text-4xl font-bold tracking-tight">Disclaimer</h1>
          </div>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">Simplified Models</h2>
            <p>
              OpenMars utilizes simplified aerospace engineering models, including the Tsiolkovsky Rocket Equation, 
              to estimate mission requirements. These models do not account for all variables present in 
              actual interplanetary missions, such as orbital perturbations, atmospheric drag during 
              ascent/descent, or complex gravity assists.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">Real-World Verification</h2>
            <p className="font-semibold text-primary">
              Results generated by OpenMars should not be used for real-world mission planning without 
              independent verification from qualified aerospace professionals and high-fidelity simulation tools.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold">Educational Use</h2>
            <p>
              This platform is intended for educational use to help users understand the relationship 
              between propulsion systems, mass fractions, and mission feasibility. It is a tool for 
              conceptual exploration and learning.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
